#!/bin/bash

UNIXHOME=$(unixhome "" "interactive")  # pretend $PS1 = "interactive"

if [[ -f ~/.bashrc ]]; then
    if ! grep -qi unixhome ~/.bashrc; then
	cat ${UNIXHOME}/etc/my-bashrc >> ~/.bashrc
    fi
else
    ln -sv ${UNIXHOME}/etc/bashrc ~/.bashrc
fi

ln --backup=t -sv ${UNIXHOME}/etc/bash_profile ~/.bash_profile

cp -pf ${UNIXHOME}/etc/unixhome ~/.unixhome
