#!/bin/sh

# Interactive-shell aliases and functions.

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias lt='ls -lt'
alias ltd='ls -ltd'
alias ll='ls -l'
alias lld='ls -ld'
alias lta='ls -ltA'
alias ltad='ls -ltAd'
alias lla='ls -lA'
alias llad='ls -lAd'
alias l1='ls -1'
alias l1d='ls -1d'
alias l1a='ls -1A'
alias l1ad='ls -1Ad'

alias golocal='PATH=$(path --prepend "$GOLOCALBIN"); GOROOT="$GOLOCALROOT"'
alias goback='PATH=$(path --remove "$GOLOCALBIN"); GOROOT="$GOORIGROOT"'

if [ -n "$SSH_CLIENT" ]; then
    # Use terminal mode when ssh'ing in, since I don't usually set up X remoting.
    alias emacs='emacs -nw'
fi

# Also define command-like aliases and functions.

. ~/.unixhome/etc/commands
