#!/bin/sh

alias newaliases="source ${UNIXHOME}/etc/aliases"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias lt='ls -lt'
alias ltd='ls -ltd'
alias ll='ls -l'
alias lld='ls -ld'
alias lta='ls -ltA'
alias ltad='ls -ltAd'
alias lla='ls -lA'
alias llad='ls -lAd'
alias l1='ls -1'
alias l1d='ls -1d'
alias l1a='ls -1A'
alias l1ad='ls -1Ad'

alias gitdown='git pull; git fetch -p'
alias gitrem='git remote -v'
alias gitbr='git branch -a'
alias gitstat='git status -unormal'
function gitnbr() { if [ $# -ne 1 ]; then echo >&2 "Need branch name."; return 99; fi; git checkout -b "$1" HEAD; git push -u origin "$1"; }
alias gitdiff='git diff'
alias gitfo='git fetch origin'
alias gitpend='git diff origin'
alias gitup='git push'
alias gitmast='git checkout master'
function gitrmbr() { if [ $# -ne 1 ]; then echo >&2 "Need branch name."; return 99; fi; git branch -D "$1"; git push origin --delete "$1"; }
