#!/bin/bash

UNIXHOME=~/GitHub/UnixHome

ALIASFILE=${UNIXHOME}/etc/aliases
[[ -r ${ALIASFILE} ]] && source ${ALIASFILE}

# Load all autocompletions if any are installed
COMPDIR=${UNIXHOME}/etc/bash_completion.d/
if [ -d "${COMPDIR}" ]; then
    for F in "${COMPDIR}"*; do
        if [ -f "${F}" ]; then
            source "${F}";
        fi
    done
fi

# Get git goodness in prompts.
source ${UNIXHOME}/etc/git-prompt.sh
PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
PROMPT_COMMAND='__git_ps1 "\u@\h:\w" "\\\$ "'
GIT_PS1_SHOWDIRTYSTATE=t
GIT_PS1_SHOWSTASHSTATE=t
GIT_PS1_SHOWUPSTREAM="verbose"

export GITBASE=git@github.com:jcburley
