#!/bin/bash

# Get the aliases and functions
if [ -f $HOME/.bashrc ]; then
        source $HOME/.bashrc
fi

PATHDIRS="$HOME/bin $HOME/googlesource/chromium/depot_tools"

for pd in $PATHDIRS; do
    [ -d $pd ] && PATH=$PATH:$pd
done

export PATH
