#!/bin/sh

# Aliases and functions that are command-like, as if on $PATH, and so
# are suitable for use in non-interactive shells. However, not all
# sshd configurations read ~/.bashrc by default.

alias gitrem='git remote -v'
alias gitbr='git branch -vv'
alias gitstat='git status -unormal'
function gitnbr() { if [ $# -ne 1 ]; then echo >&2 "Need branch name."; return 99; fi; git checkout -b "$1" HEAD; git push -u origin "$1"; }
alias gitdiff='git diff'
alias gitcor='gitfallp && git checkout --track'  # "git checkout remote"
alias gitdown='git fetch -p; git pull'
alias gitdn='git pull'
alias gitdnf='git pull -s recursive -X theirs'  # prefer upstream's changes
alias gitup='git push'
alias gitupff='git push --force-with-lease --force-if-includes'  # Better after rebase (Git >= 2.30)
alias gitupfwl='git push --force-with-lease'  # After rebase
alias gitDbr='git branch -D'
alias gitdbr='git branch -d'

function gitmbr() { head="$(git symbolic-ref refs/remotes/origin/HEAD)"; if [ $? -eq 0 ]; then echo "$(basename $head)"; else echo >&2 'Try gitsethead and re-run this.'; echo 'master'; fi; }
alias gitsethead='git remote set-head origin --auto'
alias gitmast='git checkout $(gitmbr)'
alias gitmum='git merge upstream/$(gitmbr)'
alias gitrum='git rebase upstream/$(gitmbr)'
alias gitmom='git merge origin/$(gitmbr)'
alias gitrom='git rebase origin/$(gitmbr)'

# "This PR got merged":
alias gitpr='gitmast && gitfallp && gitdn'
# "Some other PR(s) got merged":
alias gitoprm='git fetch origin $(gitmbr):$(gitmbr) && gitprune && git merge $(gitmbr)'  # Merge
alias gitoprr='git fetch origin $(gitmbr):$(gitmbr) && gitprune && git rebase $(gitmbr)' # Rebase

function gitrmbr() { if [ $# -ne 1 ]; then echo >&2 "Need branch name."; return 99; fi; O="$(git config branch.$1.remote)"; git branch -D "$1"; git push "$O" --delete "$1"; }

alias gitfall='git fetch --jobs=10 --all'
alias gitfallp='git fetch --prune --jobs=10 --all'
alias gitdone='git branch --merged'
alias gitprune='git branch -vv|grep ^\ .\*\\[[^]]\*:\ gone\\]|awk "{print \$1}"|xargs -I{} git branch -D {}'

alias gtag='git log | head -1 | cut -b 8-14'
alias gitlog1="git log --format=format:'%Cred%H%Creset %Cgreen(%an)%Creset %s'"

# Ruby/-on-Rails: prefer db:structure:load to db:schema:load if older RoR version that
# doesn't support, say, UUID as primary index.
alias nuke_and_migrate='RAILS_ENV=test bundle exec rake db:drop db:create db:structure:load db:migrate'
