#!/bin/sh

[ -r ~/.debug-profiles ] && echo "$0: profile: running" && env

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" -a -z "$BASHRC_HAS_RUN" ]; then
	. "$HOME/.bashrc"
    fi
fi

# Pull in per-session profile, if any:
export UNIX_PSP="~/.unixhome/etc/sessions/${USER}@$(hostname)"
[ -f "$UNIX_PSP/profile" ] && . "$UNIX_PSP/profile"
