#!/bin/sh
# The above and this line are excluded when appending this to an existing ~/.profile.

[ -r ~/.debug-profiles ] && echo -e "\n\n$0: ~/.profile: running" && env && set -x

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bash_profile if it exists
    if [ -f "$HOME/.bash_profile" ]; then
        # This file should source .bashrc:
	. "$HOME/.bash_profile"
    elif [ -f "$HOME/.bashrc" ]; then
        # Since no other profile file will do this, source .bashrc here:
	. "$HOME/.bashrc"
    fi
fi

# NOTE: git bash 4.4.12(2)-release (x86_64-pc-msys) (git version
# 2.16.0.windows.2) sets $USERNAME instead of $USER
[ -z "$USER" ] && export USER="$USERNAME"

# Pull in per-session profile, if any:

export UNIX_PSP="${HOME}/.unixhome/etc/sessions/${USER}@$(hostname)"
[ -f "$UNIX_PSP/profile" ] && . "$UNIX_PSP/profile"
