#!/bin/bash
# The above and this line are excluded when appending this to an existing ~/.profile.

# Pull in per-session profile, if any:

# NOTE: git bash 4.4.12(2)-release (x86_64-pc-msys) (git version
# 2.16.0.windows.2) sets $USERNAME instead of $USER
[ -z "$USER" ] && export USER="$USERNAME"

export UNIX_PSP="${HOME}/.unixhome/etc/sessions/${USER}@$(hostname)"
[ -f "$UNIX_PSP/profile" ] && . "$UNIX_PSP/profile"
