#!/bin/bash

if cp --help > /dev/null 2>&1; then
    CP=cp
else
    CP=gcp
    if ! $CP --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'gcp' invokes GNU 'cp'."
        exit 99
    fi
fi

if tail --help > /dev/null 2>&1; then
    TAIL=tail
else
    TAIL=gtail
    if ! $TAIL --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'tail' invokes GNU 'tail'."
        exit 99
    fi
fi

if [ -f ~/.bashrc ]; then
    if ! grep -F -q .unixhome/etc/bashrc ~/.bashrc; then
	$TAIL -n +3 ~/.unixhome/templates/my-bashrc >> ~/.bashrc  # Skip hashbang and subsequent lines.
        echo "$0: appended my-bashrc to ~/.bashrc"
    fi
    if grep -q '^[^#]*\[ \+-z \+"$PS1" \+\] \+&& \+return' ~/.bashrc; then
        cat >&2 <<EOF

ACTION: Change this line in ~/.bashrc:

  [ -z "\$PS1" ] && return

To read:

  # If not running interactively, just run custom bashrc and return
  if [ -z "\$PS1" ]; then
      [ -r ~/.unixhome/etc/bashrc ] && . ~/.unixhome/etc/bashrc
      return
  fi

Otherwise, 'ESC-x shell-command' 'alias' (or any particular
non-interactive alias or function, aka command, besides 'alias') will
not work.

EOF
    fi
else
    $CP -v ~/.unixhome/templates/my-bashrc ~/.bashrc
fi

if [ -f ~/.bash_profile ]; then
    if ! grep -F -q .unixhome/etc/bash_profile ~/.bash_profile; then
        $TAIL -n +3 ~/.unixhome/templates/my-bash_profile >> ~/.bash_profile  # Skip hashbang and subsequent lines.
        echo "$0: appended my-bash_profile to ~/.bash_profile"
    fi
else
    $CP -v ~/.unixhome/templates/my-bash_profile ~/.bash_profile
fi

if [ -f ~/.profile ]; then
    if ! grep -F -q .unixhome/etc/sessions ~/.profile; then
        $TAIL -n +3 ~/.unixhome/templates/my-profile >> ~/.profile  # Skip hashbang and subsequent lines.
        echo "$0: appended my-profile to ~/.profile"
    fi
else
    $CP -v ~/.unixhome/templates/my-profile ~/.profile
fi
