#!/bin/bash

# Note that AquaMacs does not read ~/.emacs.d/init.el, so maybe make a
# symlink to that from ~/.emacs.

if ln --help > /dev/null 2>&1; then
    LN=ln
else
    LN=gln
    if ! $LN --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'gln' invokes GNU 'ln'."
        exit 99
    fi
fi

if cp --help > /dev/null 2>&1; then
    CP=cp
else
    CP=gcp
    if ! $CP --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'gcp' invokes GNU 'cp'."
        exit 99
    fi
fi

mkdir -p ~/.emacs.d

if [ -f ~/.init.el ]; then
    if ! grep -qi .unixhome/.emacs.d/init.el ~/.init.el; then
	$TAIL -n +3 ${UNIXHOME}/.emacs.d/my-init.el >> ~/.init.el  # Skip package and subsequent lines.
        echo "$0: appended my-init.el to ~/.init.el"
    fi
else
    $CP -v ${UNIXHOME}/.emacs.d/init.el ~/.init.el
fi
