#!/bin/bash

# Note that AquaMacs does not read ~/.emacs.d/init.el, so maybe make a
# symlink to that from ~/.emacs.

if ln --help > /dev/null 2>&1; then
    LN=ln
else
    LN=gln
    if ! $LN --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'gln' invokes GNU 'ln'."
        exit 99
    fi
fi

if cp --help > /dev/null 2>&1; then
    CP=cp
else
    CP=gcp
    if ! $CP --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'gcp' invokes GNU 'cp'."
        exit 99
    fi
fi

if tail --help > /dev/null 2>&1; then
    TAIL=tail
else
    TAIL=gtail
    if ! $TAIL --help > /dev/null 2>&1; then
        echo >&2 "ERROR: please install GNU coreutils first, so 'tail' invokes GNU 'tail'."
        exit 99
    fi
fi

mkdir -p ~/.emacs.d

if [ -f ~/.emacs.d/init.el ]; then
    if ! grep -F -qi .unixhome/components/emacs/init.el ~/.emacs.d/init.el; then
	$TAIL -n +3 ~/.unixhome/templates/my-init.el >> ~/.emacs.d/init.el  # Skip package and subsequent lines.
        echo "$0: appended my-init.el to ~/.emacs.d/init.el"
    fi
else
    $CP -v ~/.unixhome/templates/my-init.el ~/.emacs.d/init.el
fi
